ktor:
  development: true
  deployment:
    port: 8080
    watch:
      - classes
      - resources

jwt:
#  secret: "secret"
  issuer: "http://localhost:8081/auth/realms/otus-marketplace"
  audience: "ad-users"
  realm: "otus-marketplace"
  clientId: "otus-marketplace-service"
  certUrl: "http://localhost:8081/auth/realms/otus-marketplace/protocol/openid-connect/certs"
