ktor:
  development: true
  deployment:
    port: 8080
    watch:
      - classes
      - resources
  application:
    modules:
      - ru.otus.otuskotlin.marketplace.app.ktor.ApplicationKt.module
      - ru.otus.otuskotlin.marketplace.app.ktor.ApplicationJvmKt.moduleJvm

jwt:
  #  secret: "secret"
  issuer: "http://localhost:8081/auth/realms/otus-marketplace"
  audience: "ad-users"
  realm: "otus-marketplace"
  clientId: "otus-marketplace-service"
  certUrl: "http://localhost:8081/auth/realms/otus-marketplace/protocol/openid-connect/certs"
