version: "3.3"

services:
  elasticsearch:
    build:
      context: images/elasticsearch
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build:
      context: images/kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
