/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.otus.otuskotlin.marketplace

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun appHasAGreeting() {
        assertEquals(3, 1 + 2)
    }
}
