ktor:
  development: true
  deployment:
    port: 8080
    watch:
      - classes
      - resources
#  application:
#    modules:
#      - ru.otus.otuskotlin.marketplace.app.ktor.ApplicationKt.module
#      - ru.otus.otuskotlin.marketplace.app.ktor.ApplicationJvmKt.moduleJvm
