### Create
POST http://127.0.0.1:8080/v1/ad/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsInN1YiI6InVzZXIxIiwiaXNzIjoiT3R1c0tvdGxpbiIsImdyb3VwcyI6WyJVU0VSIiwiVEVTVCJdfQ.cFOtMye2zfv8rvnAPpudAv5vrPbhVyR9VwS2DRmP67c

{
  "requestType": "create",
  "requestId": "12345",
  "ad": {
    "title": "Болт",
    "description": "КРУТЕЙШИЙ",
    "ownerId": "9435",
    "visibility": "public",
    "adType": "demand"
  },
  "debug": {
    "mode": "test"
  }
}

### Get unexisted ID
POST http://127.0.0.1:8080/v1/ad/read
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "read",
  "requestId": "12345",
  "ad": {
    "id": "99999"
  },
  "debug": {
    "stub": "badId"
  }
}

### Read With Existed id
POST http://127.0.0.1:8080/v1/ad/read
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "read",
  "requestId": "12345",
  "ad": {
    "id": "existed"
  },
  "debug": {
    "stub": "success"
  }
}

### Update
POST http://localhost:8080/v1/ad/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "update",
  "requestId": "666",
  "ad": {
    "adType": "proposal",
    "id": "updated",
    "visibility": "ownerOnly"
  },
  "debug": {
    "stub": "success"
  }
}

### Update with unexistedId
POST http://localhost:8080/v1/ad/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "update",
  "requestId": "666",
  "ad": {
    "id": "668"
  },
  "debug": {
    "stub": "badId"
  }
}

### Delete existed
POST http://localhost:8080/v1/ad/delete
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "delete",
  "requestId": "deleteId",
  "ad": {
    "id": "existed_id"
  },
  "debug": {
    "stub": "success"
  }
}

### Delete non-existed
POST http://localhost:8080/v1/ad/delete
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "delete",
  "requestId": "deleteId_unknown",
  "ad": {
    "id": "unknownId"
  },
  "debug": {
    "stub": "badId"
  }
}

### Search by string
POST http://localhost:8080/v1/ad/search
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "search",
  "requestId": "search_1",
  "adFilter": {
    "searchString": "болт"
  },
  "debug": {
    "stub": "success"
  }
}

### Search by string with error
POST http://localhost:8080/v1/ad/search
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "search",
  "requestId": "search_1",
  "adFilter": {
    "searchString": "кто тут"
  },
  "debug": {
    "stub": "badSearchString"
  }
}

### Search offer by unknown id
POST http://localhost:8080/v1/ad/offers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "offers",
  "requestId": "offer_search",
  "ad": {
    "id": "222_unknown_offer_id"
  },
  "debug": {
    "stub": "badId"
  }
}

### Find offer
POST http://localhost:8080/v1/ad/offers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "offers",
  "requestId": "offer_search",
  "ad": {
    "id": "234_offer"
  },
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

### Not find offer
POST http://localhost:8080/ad/offers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZC11c2VycyIsImlzcyI6Ik90dXNLb3RsaW4iLCJncm91cHMiOlsiVVNFUiIsIlRFU1QiXSwiaWQiOiJ1c2VyMSJ9.fE8bj8ICmYpcAbD5uyqj4NxW41RLYFpezBhfbew1pZ4


{
  "requestType": "offers",
  "requestId": "offer_search_bad",
  "ad": {
    "id": "234_offer"
  },
  "debug": {
    "stub": "badId"
  }
}




